# Generated by Django 2.0.3 on 2018-03-25 14:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.CharField(max_length=500)),
                ('agree', models.PositiveIntegerField(default=0)),
                ('disagree', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': '留言',
                'ordering': ['agree', '-created_time'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReplyFather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.CharField(max_length=500)),
                ('agree', models.PositiveIntegerField(default=0)),
                ('disagree', models.PositiveIntegerField(default=0)),
                ('object_pk', models.PositiveIntegerField(verbose_name='object ID')),
                ('is_removed', models.BooleanField(default=False, help_text='Check this box if the comment is inappropriate. A "This comment has been removed" message will be displayed instead.', verbose_name='is removed')),
            ],
            options={
                'verbose_name_plural': '一级评论',
                'ordering': ['agree', '-created_time'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReplySon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.CharField(max_length=500)),
                ('agree', models.PositiveIntegerField(default=0)),
                ('disagree', models.PositiveIntegerField(default=0)),
                ('object_pk', models.PositiveIntegerField(verbose_name='object ID')),
                ('is_removed', models.BooleanField(default=False, help_text='Check this box if the comment is inappropriate. A "This comment has been removed" message will be displayed instead.', verbose_name='is removed')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_type_set_for_replyson', to='contenttypes.ContentType', verbose_name='content type')),
                ('father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='son', to='commentAPP.ReplyFather', verbose_name='father')),
            ],
            options={
                'verbose_name_plural': '二级评论',
                'ordering': ['agree', '-created_time'],
                'abstract': False,
            },
        ),
    ]
